"""daily_briefs acwr_zone

Revision ID: 35f878fbbae0
Revises: c4e8f1a92b60
Create Date: 2026-07-25 15:46:14.497720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f878fbbae0'
down_revision: Union[str, Sequence[str], None] = 'c4e8f1a92b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_briefs', sa.Column('acwr_zone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_briefs', 'acwr_zone')
    # ### end Alembic commands ###
