"""initial schema

Revision ID: 8410a8c62705
Revises: 
Create Date: 2026-06-02 21:17:07.028504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8410a8c62705'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('source_priority', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('apparent_temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'STRAVA', 'OURA', 'APPLE_HEALTH', 'GARMIN', 'CSV', 'FIT_UPLOAD', name='data_source'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat', 'lng', 'observed_at', name='uq_weather_location_time')
    )
    op.create_index('ix_weather_location_time', 'weather_observations', ['lat', 'lng', 'observed_at'], unique=False)
    op.create_table('cycle_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'STRAVA', 'OURA', 'APPLE_HEALTH', 'GARMIN', 'CSV', 'FIT_UPLOAD', name='data_source'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Enum('MENSTRUAL', 'FOLLICULAR', 'OVULATORY', 'LUTEAL', name='cycle_phase'), nullable=True),
    sa.Column('period_length', sa.Integer(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'date', name='uq_cycle_user_source_date')
    )
    op.create_index('ix_cycle_user_date', 'cycle_records', ['user_id', 'date'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'STRAVA', 'OURA', 'APPLE_HEALTH', 'GARMIN', 'CSV', 'FIT_UPLOAD', name='data_source'), nullable=False),
    sa.Column('job_type', sa.Enum('INITIAL_SYNC', 'INCREMENTAL_SYNC', 'CSV_UPLOAD', 'FILE_UPLOAD', name='import_job_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', name='import_job_status'), nullable=False),
    sa.Column('items_total', sa.Integer(), nullable=True),
    sa.Column('items_imported', sa.Integer(), nullable=False),
    sa.Column('items_skipped_duplicates', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_jobs_user_status_created', 'import_jobs', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('STRAVA', 'OURA', name='oauth_provider'), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_user_provider')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'STRAVA', 'OURA', 'APPLE_HEALTH', 'GARMIN', 'CSV', 'FIT_UPLOAD', name='data_source'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('avg_pace_seconds_per_km', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('run_type', sa.Enum('EASY', 'LONG', 'INTERVAL', 'TEMPO', 'RECOVERY', 'RACE', 'OTHER', name='run_type'), nullable=False),
    sa.Column('run_type_source', sa.Enum('USER', 'EXTRACTED', 'DEFAULT', name='run_type_source'), nullable=False),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_title', sa.String(length=500), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('extracted_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_runs_source_external')
    )
    op.create_index('ix_runs_user_date', 'runs', ['user_id', 'date'], unique=False)
    op.create_index('ix_runs_user_type_date', 'runs', ['user_id', 'run_type', 'date'], unique=False)
    op.create_table('sleep_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'STRAVA', 'OURA', 'APPLE_HEALTH', 'GARMIN', 'CSV', 'FIT_UPLOAD', name='data_source'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_hours', sa.Float(), nullable=True),
    sa.Column('rem_sleep_hours', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('body_temperature_deviation_c', sa.Float(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'date', name='uq_sleep_user_source_date')
    )
    op.create_index('ix_sleep_user_date', 'sleep_records', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sleep_user_date', table_name='sleep_records')
    op.drop_table('sleep_records')
    op.drop_index('ix_runs_user_type_date', table_name='runs')
    op.drop_index('ix_runs_user_date', table_name='runs')
    op.drop_table('runs')
    op.drop_table('oauth_connections')
    op.drop_index('ix_import_jobs_user_status_created', table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index('ix_cycle_user_date', table_name='cycle_records')
    op.drop_table('cycle_records')
    op.drop_index('ix_weather_location_time', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_table('users')
    # ### end Alembic commands ###
