"""add run weather samples and denormalized weather summary on runs

Revision ID: 8d55e89b65e0
Revises: 8410a8c62705
Create Date: 2026-06-04 18:08:16.467543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d55e89b65e0'
down_revision: Union[str, Sequence[str], None] = '8410a8c62705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_weather_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('weather_observation_id', sa.UUID(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('apparent_temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weather_observation_id'], ['weather_observations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'elapsed_seconds', name='uq_run_weather_sample')
    )
    op.create_index('ix_run_weather_run_elapsed', 'run_weather_samples', ['run_id', 'elapsed_seconds'], unique=False)
    op.add_column('runs', sa.Column('weather_temp_start_c', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('weather_temp_end_c', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('weather_temp_max_c', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('weather_temp_min_c', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('weather_apparent_temp_max_c', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('weather_humidity_avg', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('weather_wind_speed_avg_kmh', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('weather_precipitation_total_mm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'weather_precipitation_total_mm')
    op.drop_column('runs', 'weather_wind_speed_avg_kmh')
    op.drop_column('runs', 'weather_humidity_avg')
    op.drop_column('runs', 'weather_apparent_temp_max_c')
    op.drop_column('runs', 'weather_temp_min_c')
    op.drop_column('runs', 'weather_temp_max_c')
    op.drop_column('runs', 'weather_temp_end_c')
    op.drop_column('runs', 'weather_temp_start_c')
    op.drop_index('ix_run_weather_run_elapsed', table_name='run_weather_samples')
    op.drop_table('run_weather_samples')
    # ### end Alembic commands ###
