"""add home location to users

Revision ID: f96e8b0bf478
Revises: 6da416944656
Create Date: 2026-07-11 15:13:26.329059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96e8b0bf478'
down_revision: Union[str, Sequence[str], None] = '6da416944656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('home_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('home_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'home_lng')
    op.drop_column('users', 'home_lat')
    # ### end Alembic commands ###
