from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user_id, get_session
from app.core.config import get_settings
from app.models import AskDemoAnswer
from app.schemas.analytics import AskAnswerRead, AskRequest, CitedRunRead
from app.services.ask import ASK_MODEL, generate_answer, retrieve
from app.services.cities import city_for_run
from app.services.insights import InsightUnavailableError

router = APIRouter(prefix="/ask", tags=["ask"])


@router.get("/demo-questions")
async def demo_questions_endpoint(
    session: AsyncSession = Depends(get_session),
) -> list[str]:
    """The curated demo questions, in insertion order. Empty outside demo mode."""
    if not get_settings().demo_mode:
        return []
    result = await session.execute(
        select(AskDemoAnswer.question).order_by(AskDemoAnswer.created_at)
    )
    return list(result.scalars().all())


@router.post("", response_model=AskAnswerRead)
async def ask_endpoint(
    payload: AskRequest,
    session: AsyncSession = Depends(get_session),
    user_id: UUID = Depends(get_current_user_id),
) -> AskAnswerRead:
    question = payload.question.strip()
    if not question:
        raise HTTPException(status_code=400, detail="Question must not be empty")

    if get_settings().demo_mode:
        # Free-form generation is the abuse vector in a public demo — serve
        # only the answers pre-generated by scripts/pregenerate_ask_answers.py.
        result = await session.execute(
            select(AskDemoAnswer).where(AskDemoAnswer.question == question)
        )
        canned = result.scalar_one_or_none()
        if canned is None:
            raise HTTPException(
                status_code=403,
                detail=(
                    "The demo answers its example questions only — pick one "
                    "of the suggested questions."
                ),
            )
        return AskAnswerRead(
            answer=canned.answer,
            model=canned.model,
            cited_runs=canned.cited_runs,
        )

    retrieved = await retrieve(session, user_id, question, k=5)
    if not retrieved:
        return AskAnswerRead(
            answer=(
                "No searchable runs yet — import some runs, then embed them "
                "with scripts/embed_runs.py."
            ),
            model=None,
            cited_runs=[],
        )

    try:
        answer = await generate_answer(question, retrieved)
    except InsightUnavailableError as e:
        raise HTTPException(
            status_code=503, detail="Ask temporarily unavailable"
        ) from e

    return AskAnswerRead(
        answer=answer,
        model=ASK_MODEL,
        cited_runs=[
            CitedRunRead(
                run_id=run.id,
                date=run.date,
                run_type=run.run_type,
                distance_km=run.distance_km,
                score=round(score, 3),
                city=city_for_run(run.start_lat, run.start_lng),
            )
            for run, score in retrieved
        ],
    )
